# Generated by Django 5.2.16 on 2026-07-14 12:06

import apps.events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "event_code",
                    models.CharField(
                        default=apps.events.models.generate_event_code,
                        max_length=6,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "qr_code_image",
                    models.ImageField(blank=True, null=True, upload_to="qrcodes/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("selfie", models.ImageField(upload_to="guest_selfies/")),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
