# Generated by Django 5.2.14 on 2026-05-18 14:02

import apps.search.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selfie', models.ImageField(upload_to=apps.search.models.selfie_upload_path)),
                ('search_time', models.DateTimeField(auto_now_add=True)),
                ('matched_count', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_searches', to='events.event')),
            ],
            options={
                'ordering': ('-search_time',),
            },
        ),
    ]
