# Generated by Django 5.2.16 on 2026-07-14 12:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("photos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaceEmbedding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("face_index", models.PositiveIntegerField(default=0)),
                ("embedding_vector", models.JSONField()),
                ("face_location", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="photos.photo",
                    ),
                ),
            ],
            options={
                "ordering": ("photo", "face_index"),
            },
        ),
    ]
