# Generated by Django 5.2.14 on 2026-05-18 14:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('face_index', models.PositiveIntegerField(default=0)),
                ('embedding_vector', models.JSONField()),
                ('face_location', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('photo', 'face_index'),
            },
        ),
    ]
